### ISSUE TITLE
Improve first time experience

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-azure#7]
We've received positive feedback on the code from @kevinbayes (whoot), but both Kevin and Praveen (barpr01_twitter on gitter.. not sure his github) mentioned there's work to do in getting started. Personally, I'm also finding the experience lacking, not just for build, but more importantly what to put into the blanks. Here are some important things I've cataloged, but feel free to add others.

- [ ] Add foolproof local build instructions #4
- [ ] Reduce configuration to one (or max two) short properties #5
- [ ] Explain how to derive required properties #6

cc @openzipkin/devops-tooling

**Comment by kevinbayes** [comment]
Is there a plan to create a docker container and a helper bash script to do help with the setup and entry?

**Comment by adriancole** [comment]
>
> Is there a plan to create a docker container and a helper bash script to
> do help with the setup and entry?
>
absolutely, as soon as we publish a 0.1 version (which is pending the pull
request that has the server profile)
